// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zack_module

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("auditbeat", "zack", asset.ModuleFieldsPri, AssetZack); err != nil {
		panic(err)
	}
}

// AssetZack returns asset data.
// This is the base64 encoded zlib format compressed contents of auditbeat/module/zack_module/_meta/fields.yml.
func AssetZack() string {
	return "eJxUy0EOgjAQheF9T/HCHg/Qhadw5cYM9EmbQkvaIaae3kjQ6G7yz/t6RDaLp4zRABp0pkV3lTF2BnAcS1g15GRxNgBw8ayEFOIeOLuKiYlFlA5Dg3oipBomr1iy22aeDI6l3X2PJAstPKXoQNG9AtpWWkwlb+tRftWfzFVv7/P7+ejI9sjFmVcAAAD//xn5P1c="
}
